### ISSUE TITLE
oemof paper: existing ideas and papers in process 

### ISSUE THREAD

**Issue by simnh** [oemof/organisation#4]
We can collect possible paper ideas in this issue. Additionally, we should add the papers in draft 
that already exist. 

I think the following information would be usefull (if available): 
- Topic
- Very brief discription
- Authors 
- Raw planned date of submission 
- Kind of paper (conference, peer-reviewed journal, working-paper etc) 

If these information exist, we can also move them to a wiki or an extra issue and add the link here, to keep this issue clean.

**Comment by simnh** [comment]
Oemof Core Paper: 

- Working title: oemof concept 
- The concept of oemof with graph representation and object oriented implementation, examples 
   for possible concrete energy system models (powerflow, linear programming)
- @oemof/oemof-core: @gnn , @cswh , @simnh
- End of August / End of 2016? 
- Working paper / Peer reviewed:  http://openresearchsoftware.metajnl.com/

**Comment by simnh** [comment]
Oemof solph: 

- Solph - A modular linear optimization library for energy system modelling ?
- Concept of the solph module with different small application for linear optimization problems 
(central distpatch, milp unit commitment of district heating networks, investment optimization) 
- Author (ideas): @uvchik , @simnh, @gnn 
- End of 2016? 
- ?

I think this could be worth a paper, especially with the easy extension interface for new components and constraints and various applications.

**Comment by beritRLI** [comment]
open_eGo and Frauke are working on paper(s) about energy system models as community projects;
discussions about that you find in #5

**Comment by fraukewiese** [comment]
@beritRLI could you post your idea about the paper structure in the same format here? Because I think it will be a different paper, more information here: https://github.com/oemof/organisation/issues/5

- Working Title: oemof as an example for an open and collaborative energy system modeling framework
- Brief content: A more general description of oemof as an open source, collaborative energy system framework, what does oemof do / provide to address energy system modelling challenges , everything rather easy to understand and not too much in depth
- Target group: other energy system modelers (closed and open) and potential user
- Author: frauke, @simnh, @ckaldemeyer already mentioned interest, then somebody from the collaborative paper group would be great. I guess it would be fair to have everybody who contributed significantly to oemof as authors on the paper as long as the motivation to join writing does not suffer from it :)
- Submission: ~Autumn 2016
- Peer-reviewed research paper, journal not decided yet, eventually Energy Strategy Reviews

**Comment by beritRLI** [comment]
Frauke and me had a phone call to make the discussion more easy than issue-writing.
Here the short summary:
 We agreed that there will be two papers. The paper **@fraukewiese** leads has two basic aims 
* to discuss the challenges energy system modelling is facing (integration of more and more details as e.g. different energy sectors (heat, electricity, mobility), consumer sectors and aspects like social, environmental and health issues; being understandable for a broad range of stakeholders)
* to give an overview of oemof (the functionalities, the approach..) with the objective to have something to refer to when talking about oemof in future papers or in discussions. And furthermore to analyse how oemof is dealing with the various requirements mentioned above.

The paper lead by the **@oemof/oep** Team will focus on organisational aspects especially collaborative working
* comparison of various OS coll. working groups incl. oemof 
* recommendations to improve collaborative energy system modelling

**Comment by gplssm** [comment]
I'm interested to contribute to the paper "Addressing energy system modeling challenges: The example of the Open Energy Modeling Framework - oemof". @fraukewiese could you please state if you'r interested to have me as an co-author? Secondly, could you clarify the process of writing this paper? I would like to know until which deadline we want to have the outline settled.

Btw, thanks for implicitely sharing the knowledge about the existence of overlead.com :+1:

**Comment by gplssm** [comment]
I'm interested to contribute to the paper "Solph - A modular linear optimization library for energy system modelling". I would like to do this in a double role:
1. I would like to support Uwe to get his writing tasks done and give him something back for his large contribution regarding the software development.
2. I offer to contribute personally, if you like, @simnh (knowing my missing direct contribution to SOLPH)
Could the potential authors of this paper please give feedback to the both points above. Thx!

**Comment by fraukewiese** [comment]
result of phone call with @gplessm: He will join for writing. Together with @simnh we talk on the phone on friday 11 o'clock (not the webco room because I will not have internet then)
+496151627315124
PIN 7041
Further discussion here: https://github.com/oemof/organisation/issues/7
Draft/Contents still here: https://www.overleaf.com/5254475wxgygx#/16524521/
We would like to use an open access journal, energy-related, not too expensive, if you have any ideas, we are happy to hear about that.

**Comment by simnh** [comment]
Regarding the core and solph paper (and other module related paper like powerflow, feedin or demandlib) I would like to add some general thoughts:

I suggest small groups of  people with deep knowledge of  the module being subject of the paper -
especially: 

- structure
- associated problems / shortcomings
- advantages compared to other approaches and
- major contribution to the module in it's latest version.

I think, everyone decide if that's true for her/him.   

Anyone else can contribute to the more general paper that  @fraukewiese started in  #7 if 
he or she is interested in scientific  publication about oemof and oemof concepts.
