### ISSUE TITLE
paper(s) about energy system modelling as collaborative projects 

### ISSUE THREAD

**Issue by beritRLI** [oemof/organisation#5]
The materials of AP 1 open_eGo are stored on the Vernetzen-Server (/open_eGo/Veroeffentlichungen/enviroinfo/comm_dev) and the cocument is on the git-repository (for access please ask Martin Glauer @MGlauer)

@fraukewiese started at overleaf a draft:
https://www.overleaf.com/5254475wxgygx#/16524521/

Hier ist auch das pdf dazu falls ihr Euch nicht auf Overleaf anmelden wollt (konnte das pdf irgendwie nicht hochladen, daher als .zip)
oemof_paper_suggestion.pdf.zip
@ludee 
@EvaWie

**Comment by fraukewiese** [comment]
I have talked to Eva and would rather suggest, that you keep the community project paper idea for Environinfo and we can cite this in the more general oemof paper, where the community aspect is rather part of it. I will not be of help for writing this community thing, because I do not have enough experience with that. It is also difficult to get into paper writing process. What I would prefer is a more general oemof paper with the focus what does oemof do / provide to address energy system modelling challenges (as @simnh suggested). An input about the community aspect would be great and required for that, but this would not be the main focus.
I am on a conference on thursday, so I cannot join the webko. But maybe we can talk on the phone today or friday, Berit?
Could one of you put your paper idea in the https://github.com/oemof/organisation/issues/4 with the bullet points simon suggested?
